---

- name: install ovn_host
  hosts: ovn_host
  become: yes
  tasks:

    - name: update dnf
      dnf:
        name: "*"
        state: latest

    - name: install ovn_host
      import_role:
        name: ovn_host
      vars:
        ovn_host_action: install
      tags: install_ovn_host
